config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :notices
  root 'notices#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :show, User, :id => user.id

    can :manage, Notice do |notice|
        notice.new_record? or notice.user == user
    end

    #can :manage, Notice do |notice|
    #    notice.new_record? or
    #    notice.user_id == nil or
    #    notice.user.include?(user)
    #end 
    #
    #

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
	validates_presence_of :subject, :text

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notices

  def admin?
    self.role == 1
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
	    respond_to do |format|
	      format.json { head :forbidden, content_type: 'text/html' }
	      format.html { redirect_to main_app.root_url, notice: exception.message }
	      format.js   { head :forbidden, content_type: 'text/html' }
	    end
	end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :homepage
  load_and_authorize_resource :except => [:homepage]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.where(user: current_user).order("created_at desc")
  end

  def homepage
    @notices = Notice.all.order("created_at desc")
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
    @notice.user = current_user

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:subject, :text, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def menu(description, path)
		content_tag(:li, class: "nav-item") do
			link_to description, path, class: "nav-link"
		end
	end
	def resume(text)
		truncate(raw , length: 300)
	end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
  <img src="https://image.flaticon.com/icons/svg/234/234787.svg" width="30" height="30" class="d-inline-block align-top" alt="">
  Quadro de Avisos
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <%= menu 'Homepage', root_path %>
      <%= menu 'Avisos', notices_path %>
    </ul>
    <span class="navbar-text">
      <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Editar Conta', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
      <%= link_to "Cadastro", new_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Topatudopordinheiro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/menu' %>
  <div class="text-center">
    
    <% if !alert.nil? %>
      <p class="alert alert-warning" id="alert"><%= alert %></p>
    <% else %>
      <p class="" id="alert"><%= alert %></p>
    <% end %>

    <% if !notice.nil? %>
      <p class="alert alert-info" id="notice"><%= notice %></p>
    <% else %>
      <p class="" id="notice"><%= notice %></p>
    <% end %>
  </div>
  
    <%= yield %>
  </body>
</html>

app/views/notices/_form.html.erb
<%= form_with(model: notice, local: true) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style="display: inline-block; width: 25%; padding-left: 1em;">
  <div class="field form-group" style="text-align: left;">
    <%= form.label :subject %>
    <%= form.text_field :subject, :class => "form-control", :placeholder => "Assunto" %>
  </div>

  <div class="field form-group" style="text-align: left;">
    <%= form.label :text %>
    <%= form.cktext_area :text, :class => "form-control", size: "60x12", ckeditor: { uiColor: '#AADC6E', toolbar: 'mini', language: 'br' } %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-outline-success form-control' %>
  </div>
</div>
<% end %>

app/views/notices/edit.html.erb
<div class="text-center">
	<h1>Editing Notice</h1>

	<%= render 'form', notice: @notice %>
	<%= link_to 'Show', @notice, :class =>"btn btn-outline-primary" %>
	<%= link_to 'Back', notices_path, :class =>"btn btn-outline-secondary" %>
</div>

app/views/notices/homepage.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4" style="font-weight: bold; font-family: helvetica; text-shadow: 2px 2px 2px #E2987B;">AVISOS</h1>
<hr/>
</div>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <% @notices.all.each do |notice| %>
    <div class="card mb-3 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Autor: <%= notice.user.email %></h4>
      </div>
      <div class="card-body">
        <h1 class="card-title"><%= notice.subject %></h1>
        <ul class="list-unstyled mt-3 mb-4">          
          <li style="font-size: 1.3em; text-align: justify;"><%= raw notice.text %></li>
          <small class="text-muted"><li>Data: <%=notice.created_at %></li></small>
        </ul>
        <div>
          <!--
          <%= link_to 'Ver', notice, :class => "btn btn-lg btn-outline-primary button2" %> -->
          <%= link_to 'Editar', edit_notice_path(notice), :class =>"btn btn-lg btn-outline-secondary button2" %> 
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/notices/index.html.erb
<h1>Notices</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.subject %></td>
        <td><%= raw notice.text %></td>
        <td><%= link_to 'Show', notice, :class => "btn btn-outline-info" %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice), :class => "btn btn-outline-dark" %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, :class => "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path, :class =>"btn btn-outline-success" %>

app/views/notices/new.html.erb
<div class="text-center">
	<h1>Novo Aviso</h1>

	<%= render 'form', notice: @notice %>

</div>

<%= link_to 'Back', notices_path, :class =>"btn btn-outline-secondary" %>

app/views/notices/show.html.erb
<div class="text-center">
	<div class="card" style="display: inline-block; width: 25%;">
	  <h5 class="card-header">Autor: <%= @notice.user.email %></h5>
	  <div class="card-body">
	    <h5 class="card-title">Assunto: <%= @notice.subject %></h5>
	    <p class="card-text"><%= raw @notice.text %></p>
	  </div>
	  <div style="padding-bottom: 1em;">
	  	<%= link_to 'Edit', edit_notice_path(@notice), :class =>"btn btn-outline-success" %> 
		<%= link_to 'Back', notices_path, :class =>"btn btn-outline-secondary" %>
	  </div>
	</div>
</div>